"""HAProxy generator for VTP/VortexL2.

The previous panel edition tried to restart HAProxy even when no forwarded port
existed. HAProxy validates such a config but exits because it has no listener.
This manager now treats that state as a normal, non-error state: it writes the
config for visibility, stops HAProxy, and returns a clear message.
"""
from __future__ import annotations

import os
import subprocess
from pathlib import Path
from typing import Any, Dict, List, Tuple

from vortexl2.config import ConfigManager
from vortexl2.easytier_manager import EasyTierConfigManager

HAPROXY_CFG = Path("/etc/haproxy/haproxy.cfg")
VORTEX_CFG = Path("/etc/haproxy/vortexl2.cfg")


class HAProxyManager:
    def __init__(self, config: Any = None) -> None:
        self.config = config

    def _run(self, cmd: str) -> Tuple[bool, str]:
        try:
            result = subprocess.run(cmd, shell=True, capture_output=True, text=True, timeout=30)
            return result.returncode == 0, (result.stdout.strip() or result.stderr.strip())
        except Exception as exc:
            return False, str(exc)

    def _all_tunnels(self) -> List[Any]:
        tunnels: List[Any] = []
        try:
            tunnels.extend(ConfigManager().get_all_tunnels())
        except Exception:
            pass
        try:
            tunnels.extend(EasyTierConfigManager().get_all_tunnels())
        except Exception:
            pass
        return tunnels

    def forwarding_plan(self) -> Dict[int, List[Dict[str, str]]]:
        """Return exposed_port -> backend list."""
        plan: Dict[int, List[Dict[str, str]]] = {}
        for tunnel in self._all_tunnels():
            ports = getattr(tunnel, "forwarded_ports", []) or []
            target_ip = getattr(tunnel, "remote_forward_ip", None)
            if not target_ip:
                continue
            for port in ports:
                try:
                    port_i = int(port)
                except Exception:
                    continue
                if not 1 <= port_i <= 65535:
                    continue
                backend_name = f"{getattr(tunnel, 'name', 'tunnel')}_{port_i}".replace("-", "_").replace(".", "_")
                plan.setdefault(port_i, []).append({"name": backend_name, "target": f"{target_ip}:{port_i}"})
        return plan

    def has_listeners(self) -> bool:
        return bool(self.forwarding_plan())

    def generate_config(self) -> str:
        lines = [
            "# Generated by VTP/VortexL2. Manual changes may be overwritten.",
            "global",
            "    log /dev/log local0",
            "    log /dev/log local1 notice",
            "    daemon",
            "    maxconn 20000",
            "",
            "defaults",
            "    log global",
            "    mode tcp",
            "    option tcplog",
            "    option dontlognull",
            "    timeout connect 5s",
            "    timeout client  1h",
            "    timeout server  1h",
            "",
        ]
        plan = self.forwarding_plan()
        for port in sorted(plan):
            lines.extend([
                f"frontend vortexl2_in_{port}",
                f"    bind *:{port}",
                f"    default_backend vortexl2_back_{port}",
                "",
                f"backend vortexl2_back_{port}",
                "    balance roundrobin",
                "    option tcp-check",
            ])
            for backend in plan[port]:
                lines.append(f"    server {backend['name']} {backend['target']} check inter 5s fall 2 rise 2")
            lines.append("")
        if not plan:
            lines.extend([
                "# No forwarded ports are configured yet.",
                "# HAProxy is intentionally not started in this state because it would exit with no listener.",
            ])
        return "\n".join(lines) + "\n"

    def write_config(self) -> None:
        cfg = self.generate_config()
        VORTEX_CFG.parent.mkdir(parents=True, exist_ok=True)
        VORTEX_CFG.write_text(cfg, encoding="utf-8")
        os.chmod(VORTEX_CFG, 0o644)
        HAPROXY_CFG.write_text(cfg, encoding="utf-8")
        os.chmod(HAPROXY_CFG, 0o644)

    def apply(self) -> Tuple[bool, str]:
        self.write_config()
        if not self.has_listeners():
            self._run("systemctl stop haproxy")
            return True, "HAProxy آماده است، اما چون هنوز هیچ Forwarded Port تعریف نشده، سرویس اجرا نمی‌شود. اول برای یک Tunnel پورت اضافه کنید."
        ok, msg = self._run("haproxy -c -f /etc/haproxy/haproxy.cfg")
        if not ok:
            return False, f"HAProxy config test failed: {msg}"
        self._run("systemctl enable haproxy")
        ok, msg = self._run("systemctl restart haproxy")
        return ok, msg or "HAProxy restarted"

    def remove_forward(self, port: int) -> Tuple[bool, str]:
        if self.config and hasattr(self.config, "remove_port"):
            self.config.remove_port(int(port))
            return self.apply()
        return False, "No tunnel selected"

    def add_forward(self, port: int) -> Tuple[bool, str]:
        if self.config and hasattr(self.config, "add_port"):
            self.config.add_port(int(port))
            return self.apply()
        return False, "No tunnel selected"
